### PR TITLE
update impact field

### PR DESCRIPTION
**Pull request by dpensi**
# Description

updated impact field

Fixes CCXDEV-5613

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing steps
None

### CODE REVIEW

**Review by tisnik — APPROVED** [review]
Seems ok, but it break other things as can be seen on CI

**Review by Bee-lee — COMMENTED** [review]
@dpensi I don't think we need to provide the string representation, it is never used or displayed anywhere. We should keep it consistent with `likelihood` which behaves in the same way

**Comment by dpensi** [comment]
@Bee-lee are we sure? in the task it's written 

I```
deally (but not required), the RHEL format can be adopted: 

"impact": \{ "name": "string", "impact": 0 } ([https://console.redhat.com/docs/api/insights-results-aggregator#operations-prod-getContent]).
```

**Comment by Bee-lee** [comment]
@dpensi I mean, we can keep it here, but our mockups don't accommodate for the string anywhere, so I won't return it anyway in the /rule/ endpoint for which this is needed. 

btw that API provides a lot of additional and unused data in so many endpoints for some reason

**Review by tisnik — APPROVED** [review]
ok

**Review by juandspy — APPROVED** [review]

**Pull request merged**
