### PR TITLE
moved some types from the content service and fixed more info

### PR DESCRIPTION
**Pull request by Sergey1011010**
## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Refactor (refactoring code, removing useless files)

## Testing steps

`make style; and make test`

### CODE REVIEW

**Review by tisnik — APPROVED** [review]
seems legit

**Review by joselsegura — APPROVED** [review]
lgtm

**Review by bond95 — COMMENTED** [review]
Do we need `RuleContent` in utils? For this cases I think would be nice to adding also link to PR which require this change.

**Comment by Sergey1011010** [comment]
@bond95, yup, it's to decrease amount of circular dependencies(see aggregator-data repo, which depended on operator-utils and content-service

**Pull request merged**
